[package]
name = "APS"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.215", features = ["derive"] }
toml = "0.8.19"
rand = "0.8"         # Проверить последнюю версию на crates.io
rand_distr = "0.4"

